Project2
GTag123/tinkoff-java pull request #6
Opened 2023-11-05 20:49 UTC by GTag123

2023-12-03 08:27 UTC, strelchm requested changes

2023-12-03 08:27 UTC, strelchm commented on src/main/java/edu/project2/Main.java
> +            System.out.println("Неверный ввод");
not important: откуда пользователь поймет, что минимальная размерность = 9?

2023-12-03 08:27 UTC, strelchm commented on src/main/java/edu/project2/MazeRenderer.java
> +    public String render(Maze maze, List<Coordinate> path) {
Можно ли совместить два метода данного класса в один (данный), т к дублирование / логика +- таже

2023-12-03 08:27 UTC, strelchm commented on src/main/java/edu/project2/MazeRenderer.java
> +    public String render(Maze maze, List<Coordinate> path) {
либо если оставить два метода, то сделать один на основе другого

2023-12-03 08:27 UTC, strelchm commented on src/main/java/edu/project2/MazeGenerator.java
> +    public Maze generate(int height, int width, Random random) {
Не понятен, нужен ли Random в аргументах. Похоже его можно инкапсулировать в классе и убрать из аргументов метода

2023-12-03 08:53 UTC, strelchm commented on src/main/java/edu/project2/Main.java
> +import edu.project2.Solvers.BFSMazeSolver;
Такой нейминг пакетов не общепринятый (возможно он взят из C#?). Для java лучше изменить название пакета на **edu.project2.solvers**. Для подробностей можно посмотреть [javadoc](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html)

2023-12-03 19:34 UTC, GTag123 commented on src/main/java/edu/project2/MazeGenerator.java
> +    public Maze generate(int height, int width, Random random) {
Он нужен мне в тестах, не знаю как без передачи определенного сида протестировать корректность лабиринта

2023-12-03 19:41 UTC, strelchm commented on src/main/java/edu/project2/MazeGenerator.java
> +    public Maze generate(int height, int width, Random random) {
принял, оставляем. Несколько казалось, что со стороны основного кода несколько неявен random как аргумент

2024-01-07 22:41 UTC, strelchm approved these changes

2024-07-18 12:29 UTC, merged